from database.connection import databaseConfig


def createTables():
    db_config = databaseConfig()
    cursor = db_config.cursor()

    # USERS TABLE
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS USERS (
        USERID INTEGER PRIMARY KEY AUTOINCREMENT,

        NAME TEXT NOT NULL,
        EMAIL TEXT NOT NULL UNIQUE,
        PHONE_NUMBER TEXT UNIQUE,

        PASSWORD TEXT NOT NULL,

        PROFILE_IMAGE TEXT,

        ROLE TEXT DEFAULT 'user',
        STATUS INTEGER DEFAULT 1,

        CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
    );
    """)

    # PRODUCTS TABLE
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS PRODUCTS (
        PRODUCTID INTEGER PRIMARY KEY AUTOINCREMENT,

        NAME TEXT NOT NULL,
        DESCRIPTION TEXT,

        CATEGORY TEXT NOT NULL,

        IMAGE_URL TEXT,

        PRICE REAL NOT NULL CHECK (PRICE >= 0),
        STOCK INTEGER DEFAULT 0 CHECK (STOCK >= 0),

        ACTIVE INTEGER DEFAULT 1,

        CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
    );
    """)

    # ORDERS TABLE
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS ORDERS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,

        ORDER_ID INTEGER NOT NULL,
        USER_ID INTEGER NOT NULL,
        PRODUCT_ID INTEGER NOT NULL,

        PRODUCT_NAME TEXT NOT NULL,
        PRODUCT_PRICE REAL NOT NULL,

        QUANTITY INTEGER NOT NULL DEFAULT 1,
        TOTAL_PRICE REAL,

        CUSTOMER_NAME TEXT,
        PHONE TEXT,
        ADDRESS TEXT,
        CITY TEXT,
        PINCODE TEXT,

        ORDER_STATUS TEXT DEFAULT 'PENDING',
        PAYMENT_METHOD TEXT,
        PAYMENT_STATUS TEXT DEFAULT 'PENDING',

        CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
    );
        """)

    # ORDER ITEMS TABLE
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,

        ORDERID INTEGER NOT NULL,
        PRODUCTID INTEGER NOT NULL,

        PRODUCTNAME TEXT NOT NULL,
        PRODUCTPRICE REAL NOT NULL,

        QUANTITY INTEGER NOT NULL DEFAULT 1,
        TOTALPRICE REAL
    );
    """)

    # CART TABLE
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS CART (
        CARTID INTEGER PRIMARY KEY AUTOINCREMENT,

        USERID INTEGER NOT NULL,
        PRODUCTID INTEGER NOT NULL,

        QUANTITY INTEGER NOT NULL DEFAULT 1,
        PRICE REAL NOT NULL,

        CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,

        FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
        FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE
    );
    """)

    db_config.commit()
    cursor.close()
    db_config.close()

    if __name__ == "__main__":
        createTables()
        print("Tables created successfully ✅")